org.gradle.jvmargs = -Xmx3G
org.gradle.caching = true

loom.ignoreDependencyLoomVersionValidation=true

archives_base_name = createaddition
mod_version = 1.7.0-fly.26.2-beta.9
maven_group = com.mrh0.createaddition

minecraft_version = 26.2
minecraft_dependency_version = 26.2

fabric_loader_version = 0.19.3
fabric_api_version = 0.155.0+26.2

create_fabric_version = 26.2-rc-2-6.0.9-1
create_fabric_version_range = >=6.0.9-1

team_reborn_energy_version = 5.0.0

rei_version = 26.2.820+fabric
architectury_version = 21.0.7+fabric
basic_math_version = 0.6.1
createreiviewer_version = 1.0.0-fly.26.2-beta.4
